---
title: "Research"
---

<style>
body {
text-align: justify}
</style>


<br>
<p style="color:black"> My research agenda covers civil conflict, political violence, terrorism, state of emergency, and electoral behavior utilizing originally collected and quantified textual and visual data such as newspapers and satellite imagery. </p>

<br>
<p style="color:black"> My dissertation examines the domestic and international causes for the declarations of the state of emergencies, as well as the consequences of the state of emergencies on interstate defense cooperation agreements. This work develops an original hand-coded cross-sectional time-series newspaper data of emergency declarations in Latin America (1980 to 2018) and employs various quantitative and qualitative research methods. </p>

<br>
<p style="color:black"> My research efforts aim to expand the theoretical frameworks within the field of political violence literature. To this end, my first  <a href="https://journals.sagepub.com/doi/10.1177/00223433221126715">study</a> (published in the <i>Journal of Peace Research</i>), in collaboration with Dr. Kemahlıoğlu (Sabancı University) and Dr. Bayer (Koç University), provides evidence demonstrating how the incumbent party avoids taking responsibility for acts of terrorism. This study focused on nine hundred counties, as administrative municipalities, over twenty years of single government incumbency in Turkey, indicating that the incumbent party utilizes local governance and resources in their narratives, effectively deflecting responsibility in national elections.  </p>

<br>
<p style="color:black"> My second <a href="https://www.tandfonline.com/doi/full/10.1080/09546553.2023.2252104">study</a> (published in <i>Terrorism and Political Violence</i>), conducted in collaboration with Dr. Kemahlıoğlu and Dr. Bayer, examines the performance of the banking sector in the face of terror attacks. Alongside confirming the conflict trap theory, which posits that as civil conflict persists, economic development deteriorates, and people in poor living conditions become further entangled in the conflict, our findings highlighted that financial indicators are negatively affected by political violence. Furthermore, ownership of banks and the region where the violence occurs play a significant role in this association.</a> </p>

